---
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user: ansible
ansible_ssh_pass: "{{reservoir_user_password}}"
ansible_become_pass: "{{reservoir_user_password}}"
is_docker_container: true
