---
- name: Setup Docker Swarm Cluster and Overlay Network
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    # Initialize Docker Swarm on Sycorax
    - name: Initialize Docker Swarm (on manager node)
      command: docker swarm init
      when: inventory_hostname in groups['swarm_manager']
      register: swarm_init
      ignore_errors: yes

    # Retrieve Swarm Join Token
    - name: Get Docker Swarm join-token for worker
      command: docker swarm join-token -q worker
      register: join_token
      when: inventory_hostname in groups['swarm_manager'] and swarm_init is succeeded

    # Join Worker Nodes to Swarm
    - name: Join Docker Swarm (on worker nodes)
      command: "docker swarm join --token {{ hostvars[groups['swarm_manager'][0]]['join_token'].stdout }} {{ hostvars[groups['swarm_manager'][0]]['ansible_default_ipv4']['address'] }}:2377"
      when: inventory_hostname in groups['swarm_workers']
      ignore_errors: yes

    # Create Overlay Network
    - name: Create Docker Overlay Network
      command: docker network create --driver overlay --attachable slurm_network
      when: inventory_hostname in groups['swarm_manager']
      run_once: true
