- hosts: aegypti
  become: yes
  become_method: sudo
  tasks:
    - name: Create gitlab runner config file
      copy:
        dest: "/gitlab-runner/config/config.toml"
        content: |
          concurrent = 1
          check_interval = 0

          [session_server]
            session_timeout = 1800

          [[runners]]
            name = "aegypti-runner"
            url = "https://gitlab.com/"
            token = "{{gitlab_runner_token}}"
            executor = "docker"
            [runners.custom_build_dir]
            [runners.docker]
              tls_verify = false
              image = "ecohealthalliance/reservoir:rpkg"
              privileged = false
              disable_entrypoint_overwrite = false
              oom_kill_disable = false
              disable_cache = false
              volumes = ["/cache", "/home/shared:/home/shared:ro"]
              shm_size = 0
            [runners.cache]
              [runners.cache.s3]
              [runners.cache.gcs]

    - name: Start gitlab runner
      docker_compose:
        project_name: gitlab_runner
        restarted: true
        definition:
          version: '2'
          services:
            gitlab-runner:
              restart: always
              image:  "gitlab/gitlab-runner:latest"
              volumes:
                - "/gitlab-runner/config:/etc/gitlab-runner"
                - "/var/run/docker.sock:/var/run/docker.sock"

  vars_files:
    - secure.yml
