- hosts: cloudwatch_machines
  become: yes
  become_method: sudo
  tasks:
    - name: copy .env file
      become: yes
      copy:
        src: .env
        dest: "/root/.env"
        owner: root
        group: root
        mode: '0700'
    - name: Get env file content
      become: yes
      no_log: true
      slurp:
        src: /root/.env
      register: env_file_content
    - name: Parse env file and load into fact
      become: yes
      set_fact:
        env_vars: "{{ ('{' + (env_file_content.content | b64decode).split('\n') | select | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"
    - name: create AWS cred dir if it doesn't exist
      file:
        path: /root/.aws
        state: directory
        mode: '0700'
    - name: create AWS config file
      copy:
        dest: /root/.aws/config
        content: |
          [AmazonCloudWatchAgent]
          region={{ env_vars["AWS_REGION"] }}
    - name: create AWS credentials file
      copy:
        dest: /root/.aws/credentials
        content: |
          [AmazonCloudWatchAgent]
          aws_access_key_id={{ env_vars["AWS_ACCESS_KEY_ID"] }}
          aws_secret_access_key={{ env_vars["AWS_SECRET_ACCESS_KEY"] }}
    - name: install CloudWatch Agent
      apt:
        deb: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    - name: check ansible_hostname
      debug:
        var: ansible_hostname
    - name: copy over config file with log filtering for prospoero
      copy:
        src: CloudWatch/config_with_log.json
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
      when: ansible_hostname == "prospero"
    - name: copy over config file without log filtering for other servers
      copy:
        src: CloudWatch/config.json
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
      when: ansible_hostname != "prospero"
    - name: start the CloudWatch Agent
      command: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m onPremise -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json"
