version: '3.8'

services:
  controller:
    image: ${controller_image}
    deploy:
      resources:
        limits:
          cpus: '20'
          memory: 200000M
      placement:
        constraints:
          - node.labels.node_type == aegypti
    container_name: controller
    privileged: true
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    restart: always
    hostname: ${HOSTNAME}
    networks:
      - slurm
    ports:
      - "22024:22"
      - "8786:8787"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: megatron
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6819
      ACCOUNTING_STORAGE_HOST: localhost
      ACCOUNTING_STORAGE_PORT: 3306
      COMPUTE_NODES: aegypti_worker
      CONTROL_MACHINE: controller.local.dev

  aegypti_worker:
    image: ${worker_image}
    deploy:
      resources:
        limits:
          cpus: '40'
          memory: 200000M
      placement:
        constraints:
          - node.labels.node_type == aegypti
    depends_on:
      - controller
    container_name: aegypti_worker
    privileged: true
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    restart: always
    hostname: aegypti_worker.local.dev
    networks:
      - slurm
    ports:
      - "22023:22"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      PARTITION_NAME: non-gpu
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller

  sycorax_worker:
    image: ${worker_image}
    deploy:
      resources:
        limits:
          cpus: '128'
          memory: 250000M
      placement:
        constraints:
            - node.labels.node_type == sycorax
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    networks:
      - slurm
    ports:
      - "22025:22"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      PARTITION_NAME: gpu
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller

networks:
  slurm:
    external: true
    driver: overlay
