version: '3.8'

services:
  controller:
    image: ${controller_image}
    deploy:
      labels:
        my_label: controller
      resources:
        limits:
          cpus: '128'
          memory: 250000M
      placement:
        constraints:
          - node.labels.node_type == sycorax
    privileged: true
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "/work/.secrets:/.secret"
    restart: always
    hostname: controller.local.dev
    networks:
      - slurm
    ports:
      - "22023:22"
      - "8786:8787"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: megatron
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6819
      ACCOUNTING_STORAGE_HOST: localhost
      ACCOUNTING_STORAGE_PORT: 3306
      COMPUTE_NODES: sycorax_worker,aegypti_worker,prospero_worker
      CONTROL_MACHINE: controller.local.dev
       

  sycorax_worker:
    image: ${worker_image}
    deploy:
      labels:
        my_label: sycorax_worker
      resources:
        limits:
          cpus: '128'
          memory: 250000M
      placement:
        constraints:
          - node.labels.node_type == sycorax
    privileged: true
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "/work/.secrets:/.secret"
    restart: always
    hostname: sycorax_worker.local.dev
    networks:
      - slurm
    ports:
      - "22025:22"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      CONTROL_MACHINE: controller.local.dev
     


  aegypti_worker:
    image: ${worker_image}
    deploy:
      labels:
        my_label: aegypti_worker
      resources:
        limits:
          cpus: '40'
          memory: 200000M
      placement:
        constraints:
          - node.labels.node_type == aegypti
    privileged: true
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "/work/.secrets:/.secret"
    restart: always
    hostname: aegypti_worker.local.dev
    networks:
      - slurm
    ports:
      - "22024:22"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      PARTITION_NAME: non-gpu
      CONTROL_MACHINE: controller.local.dev


  prospero_worker:
    image: ${worker_image}
    deploy:
      labels:
        my_label: prospero_worker
      resources:
        limits:
          cpus: '72'
          memory: 51500M
      placement:
        constraints:
          - node.labels.node_type == prospero
    privileged: true
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "/work/.secrets:/.secret"
    restart: always
    hostname: prospero_worker.local.dev
    networks:
      - slurm
    ports:
      - "22026:22"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      CONTROL_MACHINE: controller.local.dev

  
  

networks:
  slurm:
    external: true
    driver: overlay