version: '3.1'  # Ensure version 3.8 for GPU support

services:
  prospero_worker:
    image: ${worker_image}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
        limits:
          cpus: '70'
          memory: 51500M
    container_name: prospero_worker
    privileged: true
    volumes:
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    restart: always
    hostname: prospero.ecohealthalliance.org
    networks:
      - slurm
    ports:
      - "22026:22"
    environment:
      USER: ansible
      USERID: 111
      ROOT: 'true'
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      PARTITION_NAME: non-gpu
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller

networks:
  slurm:
    name: slurm_network
