version: '3.1'

services:
  controller:
    image:  ${controller_image}
    container_name: controller
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "/secret:/.secret"
    restart: always
    hostname: controller.local.dev
    networks:
      - slurm
    ports:
      - 8787:8787
    environment:
      USER: ansible
      USERID: 1111
      ROOT: true
      PASSWORD: ${RESERVOIR_USER_PASSWORD}
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: megatron
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6819
      ACCOUNTING_STORAGE_HOST: localhost
      ACCOUNTING_STORAGE_PORT: 3306
      COMPUTE_NODES: worker01 worker02 worker03 worker04
      PARTITION_NAME: docker
      CONTROL_MACHINE: controller.local.dev
    
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32G
        reservations:
          cpus: '4'
          memory: 16G

  worker01:
    image: ${worker_image}
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    restart: always
    hostname: worker01.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
          devices:
            - capabilities: ["gpu"]

  worker02:
    image: ${worker_image}
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    restart: always
    hostname: worker02.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
          devices:
            - capabilities: ["gpu"]


  worker03:
    image: ${worker_image}
    depends_on:
      - controller
    container_name: worker03
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    restart: always
    hostname: worker03.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
          devices:
            - capabilities: ["gpu"]                     


worker04:
    image: ${worker_image}
    depends_on:
      - controller
    container_name: worker04
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/home:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/local:/local"
      - "/shared:/shared"
      - "/home/crontabs/${HOSTNAME}/:/var/spool/cron/crontabs"
      - "/archive:/archive"
      - "/work:/work"
      - "/reservoir_host_keys:/etc/ssh/host_keys"
      - "./secret:/.secret"
    restart: always
    hostname: worker04.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
          devices:
            - capabilities: ["gpu"]

networks:
  slurm:
    name: slurm_network

