---
ansible_host: aegypti.ecohealthalliance.org
ansible_port: 22022
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter: /usr/bin/python3
ansible_user: ansible
ansible_ssh_pass: "{{reservoir_user_password}}"
ansible_become_pass: "{{reservoir_user_password}}"
is_docker_container: true
# For NFS systems user homes should only be set up on one of the hosts.
create_user_homes: no

