version: '3.8'

services:
  network-test:
    image: alpine
    command: tail -f /dev/null
    networks:
      - slurm_workload
    deploy:
      replicas: 3

networks:
  slurm_workload:
    external: true
